# Generated by Django 5.2.9 on 2025-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateTimeField(auto_now_add=True)),
                ('compteur_niveau', models.IntegerField(default=0)),
                ('traite_par', models.CharField(default='Inconnu', max_length=100)),
                ('note_intervention', models.TextField(default='RAS')),
            ],
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='lumiere',
        ),
    ]
