# Generated by Django 5.2.9 on 2025-12-23 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_incident_remove_dht11_lumiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='compteur_niveau',
            new_name='counter',
        ),
        migrations.AddField(
            model_name='incident',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='max_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='op1_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='op1_comment',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='incident',
            name='op2_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='op2_comment',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='incident',
            name='op3_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='op3_comment',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dht11',
            name='hum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
