# Generated by Django 5.2.9 on 2026-01-03 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_rename_compteur_niveau_incident_counter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='op1_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='op2_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='op3_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='temp_max_autorisee',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='incident',
            name='temp_min_autorisee',
            field=models.FloatField(default=2.0),
        ),
        migrations.CreateModel(
            name='OperateurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('niveau', models.PositiveSmallIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
