# Generated by Django 5.2.7 on 2026-01-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_incident_op1_saved_at_incident_op2_saved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(default=2, verbose_name='Température minimale (°C)')),
                ('temp_max', models.FloatField(default=8, verbose_name='Température maximale (°C)')),
            ],
            options={
                'verbose_name': 'Seuil de température',
                'verbose_name_plural': 'Seuils de température',
            },
        ),
    ]
