# Generated by Django 5.2.9 on 2026-01-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_alter_dht11_id_alter_incident_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operateurprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seuiltemperature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
